### ISSUE TITLE
docker image not working

### ISSUE THREAD

**Issue by ismkdc** [haravich/fake-smtp-server#13]
the latest docker image not working. Throwing an exception when trying to deploy my docker server.
thx :)

**Comment by kgk** [comment]
this broke for use too.

**Comment by 4bdulla** [comment]
its not working for me as well. here is the std output:
```
Starting MailCatcher v0.9.0
2024-04-23T13:16:59.315428505Z <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:160:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)
2024-04-23T13:16:59.315474096Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
2024-04-23T13:16:59.315484762Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:40:in `require'
2024-04-23T13:16:59.315506646Z 	from /usr/local/bundle/gems/sqlite3-1.7.3-x86_64-linux/lib/sqlite3.rb:6:in `rescue in <top (required)>'
2024-04-23T13:16:59.315532069Z 	from /usr/local/bundle/gems/sqlite3-1.7.3-x86_64-linux/lib/sqlite3.rb:2:in `<top (required)>'
2024-04-23T13:16:59.315539989Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:16:59.315578544Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:16:59.315589047Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher/mail.rb:6:in `<top (required)>'
2024-04-23T13:16:59.315597606Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:16:59.315605362Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:16:59.315612799Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher/smtp.rb:5:in `<top (required)>'
2024-04-23T13:16:59.315620473Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:16:59.315628055Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:16:59.315635882Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:183:in `block (2 levels) in run!'
2024-04-23T13:16:59.315644115Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:239:in `rescue_port'
2024-04-23T13:16:59.315651516Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:182:in `block in run!'
2024-04-23T13:16:59.315659071Z 	from /usr/local/bundle/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
2024-04-23T13:16:59.315666832Z 	from /usr/local/bundle/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
2024-04-23T13:16:59.315674721Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:180:in `run!'
2024-04-23T13:16:59.315682212Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/bin/mailcatcher:6:in `<top (required)>'
2024-04-23T13:16:59.315689819Z 	from /usr/local/bundle/bin/mailcatcher:25:in `load'
2024-04-23T13:16:59.315696832Z 	from /usr/local/bundle/bin/mailcatcher:25:in `<main>'
2024-04-23T13:16:59.315706836Z <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)
2024-04-23T13:16:59.315715553Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:16:59.315723331Z 	from /usr/local/bundle/gems/sqlite3-1.7.3-x86_64-linux/lib/sqlite3.rb:6:in `rescue in <top (required)>'
2024-04-23T13:16:59.315730918Z 	from /usr/local/bundle/gems/sqlite3-1.7.3-x86_64-linux/lib/sqlite3.rb:2:in `<top (required)>'
2024-04-23T13:16:59.315738772Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:16:59.315746683Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:16:59.315754284Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher/mail.rb:6:in `<top (required)>'
2024-04-23T13:16:59.315772980Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:16:59.315782408Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:16:59.315790489Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher/smtp.rb:5:in `<top (required)>'
2024-04-23T13:16:59.315798509Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:16:59.315806216Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:16:59.315814275Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:183:in `block (2 levels) in run!'
2024-04-23T13:16:59.315821911Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:239:in `rescue_port'
2024-04-23T13:16:59.315829448Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:182:in `block in run!'
2024-04-23T13:16:59.315837024Z 	from /usr/local/bundle/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
2024-04-23T13:16:59.315844830Z 	from /usr/local/bundle/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
2024-04-23T13:16:59.315852923Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:180:in `run!'
2024-04-23T13:16:59.315860715Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/bin/mailcatcher:6:in `<top (required)>'
2024-04-23T13:16:59.315868482Z 	from /usr/local/bundle/bin/mailcatcher:25:in `load'
2024-04-23T13:16:59.315875954Z 	from /usr/local/bundle/bin/mailcatcher:25:in `<main>'
2024-04-23T13:16:59.315885234Z <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require': Error relocating /usr/local/bundle/gems/sqlite3-1.7.3-x86_64-linux/lib/sqlite3/3.2/sqlite3_native.so: posix_fallocate64: symbol not found - /usr/local/bundle/gems/sqlite3-1.7.3-x86_64-linux/lib/sqlite3/3.2/sqlite3_native.so (LoadError)
2024-04-23T13:16:59.315894491Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:16:59.315902246Z 	from /usr/local/bundle/gems/sqlite3-1.7.3-x86_64-linux/lib/sqlite3.rb:4:in `<top (required)>'
2024-04-23T13:16:59.315910178Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:16:59.315917625Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:16:59.315925124Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher/mail.rb:6:in `<top (required)>'
2024-04-23T13:16:59.315932594Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:16:59.315940354Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:16:59.315948322Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher/smtp.rb:5:in `<top (required)>'
2024-04-23T13:16:59.315963510Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:16:59.315971470Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:16:59.315979411Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:183:in `block (2 levels) in run!'
2024-04-23T13:16:59.315986815Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:239:in `rescue_port'
2024-04-23T13:16:59.315994539Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:182:in `block in run!'
2024-04-23T13:16:59.316001740Z 	from /usr/local/bundle/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
2024-04-23T13:16:59.316009606Z 	from /usr/local/bundle/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
2024-04-23T13:16:59.316017270Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:180:in `run!'
2024-04-23T13:16:59.316024585Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/bin/mailcatcher:6:in `<top (required)>'
2024-04-23T13:16:59.316032289Z 	from /usr/local/bundle/bin/mailcatcher:25:in `load'
2024-04-23T13:16:59.316039642Z 	from /usr/local/bundle/bin/mailcatcher:25:in `<main>'
2024-04-23T13:20:41.484133197Z Starting MailCatcher v0.9.0
2024-04-23T13:20:41.741818133Z <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:160:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)
2024-04-23T13:20:41.741871552Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
2024-04-23T13:20:41.741882470Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:40:in `require'
2024-04-23T13:20:41.741890455Z 	from /usr/local/bundle/gems/sqlite3-1.7.3-x86_64-linux/lib/sqlite3.rb:6:in `rescue in <top (required)>'
2024-04-23T13:20:41.741917471Z 	from /usr/local/bundle/gems/sqlite3-1.7.3-x86_64-linux/lib/sqlite3.rb:2:in `<top (required)>'
2024-04-23T13:20:41.741927881Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:20:41.741936622Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:20:41.741945415Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher/mail.rb:6:in `<top (required)>'
2024-04-23T13:20:41.741953938Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:20:41.741963362Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:20:41.741971544Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher/smtp.rb:5:in `<top (required)>'
2024-04-23T13:20:41.741980273Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:20:41.742011807Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:20:41.742021059Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:183:in `block (2 levels) in run!'
2024-04-23T13:20:41.742028745Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:239:in `rescue_port'
2024-04-23T13:20:41.742037016Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:182:in `block in run!'
2024-04-23T13:20:41.742045369Z 	from /usr/local/bundle/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
2024-04-23T13:20:41.742053709Z 	from /usr/local/bundle/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
2024-04-23T13:20:41.742062052Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:180:in `run!'
2024-04-23T13:20:41.742070198Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/bin/mailcatcher:6:in `<top (required)>'
2024-04-23T13:20:41.742078726Z 	from /usr/local/bundle/bin/mailcatcher:25:in `load'
2024-04-23T13:20:41.742086279Z 	from /usr/local/bundle/bin/mailcatcher:25:in `<main>'
2024-04-23T13:20:41.742097405Z <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)
2024-04-23T13:20:41.742105972Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:20:41.742114137Z 	from /usr/local/bundle/gems/sqlite3-1.7.3-x86_64-linux/lib/sqlite3.rb:6:in `rescue in <top (required)>'
2024-04-23T13:20:41.742122218Z 	from /usr/local/bundle/gems/sqlite3-1.7.3-x86_64-linux/lib/sqlite3.rb:2:in `<top (required)>'
2024-04-23T13:20:41.742130265Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:20:41.742138392Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:20:41.742146968Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher/mail.rb:6:in `<top (required)>'
2024-04-23T13:20:41.742155398Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:20:41.742163695Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:20:41.742172176Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher/smtp.rb:5:in `<top (required)>'
2024-04-23T13:20:41.742180419Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:20:41.742188620Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:20:41.742196611Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:183:in `block (2 levels) in run!'
2024-04-23T13:20:41.742215459Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:239:in `rescue_port'
2024-04-23T13:20:41.742224253Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:182:in `block in run!'
2024-04-23T13:20:41.742232184Z 	from /usr/local/bundle/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
2024-04-23T13:20:41.742240400Z 	from /usr/local/bundle/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
2024-04-23T13:20:41.742248304Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:180:in `run!'
2024-04-23T13:20:41.742272113Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/bin/mailcatcher:6:in `<top (required)>'
2024-04-23T13:20:41.742283779Z 	from /usr/local/bundle/bin/mailcatcher:25:in `load'
2024-04-23T13:20:41.742291658Z 	from /usr/local/bundle/bin/mailcatcher:25:in `<main>'
2024-04-23T13:20:41.742301947Z <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require': Error relocating /usr/local/bundle/gems/sqlite3-1.7.3-x86_64-linux/lib/sqlite3/3.2/sqlite3_native.so: posix_fallocate64: symbol not found - /usr/local/bundle/gems/sqlite3-1.7.3-x86_64-linux/lib/sqlite3/3.2/sqlite3_native.so (LoadError)
2024-04-23T13:20:41.742313516Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:20:41.742321784Z 	from /usr/local/bundle/gems/sqlite3-1.7.3-x86_64-linux/lib/sqlite3.rb:4:in `<top (required)>'
2024-04-23T13:20:41.742330442Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:20:41.742338626Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:20:41.742346830Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher/mail.rb:6:in `<top (required)>'
2024-04-23T13:20:41.742355253Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:20:41.742363489Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:20:41.742371743Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher/smtp.rb:5:in `<top (required)>'
2024-04-23T13:20:41.742380006Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:20:41.742387753Z 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
2024-04-23T13:20:41.742395904Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:183:in `block (2 levels) in run!'
2024-04-23T13:20:41.742403982Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:239:in `rescue_port'
2024-04-23T13:20:41.742412048Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:182:in `block in run!'
2024-04-23T13:20:41.742420018Z 	from /usr/local/bundle/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
2024-04-23T13:20:41.742437396Z 	from /usr/local/bundle/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
2024-04-23T13:20:41.742446069Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:180:in `run!'
2024-04-23T13:20:41.742453845Z 	from /usr/local/bundle/gems/mailcatcher-0.9.0/bin/mailcatcher:6:in `<top (required)>'
2024-04-23T13:20:41.742462169Z 	from /usr/local/bundle/bin/mailcatcher:25:in `load'
2024-04-23T13:20:41.742469974Z 	from /usr/local/bundle/bin/mailcatcher:25:in `<main>'
```

**Comment by AliakbarSu** [comment]
Same it has broken for me too

**Comment by ebell451** [comment]
The last image that works is haravich/fake-smtp-server:20240407

**Comment by joarobles** [comment]
Is this project still alive?

**Comment by haravich** [comment]
Latest image should have the fix
